#### application.yml
spring:
  application:
    name: demo01
profiles:
  active: dev
####  application-dev.yml
server:
  port: 8001
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mapper-locations: classpath:com/example/service/*/mapper/*.xml
global-config:
  db-config:
    logic-delete-value: 1
logic-not-delete-value: 0

jackson:
  date-format: yyyy-MM-dd HH:mm:ss
time-zone: GMT+8
